name: Rust

on: push

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
      
    - name: Run clippy
      run: cargo clippy
